### ISSUE TITLE
harmonize timestamp types

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#117]
Various types are used throughout the code base to capture dates (with time). By convention we count the number of milliseconds since the Unix epoch, but even for this number the types `Duration`, `u64`, and `BFieldElement` are used rather interchangeably. Note that `BFieldElement` is used for consensus-critical data structures such as `Block` and `Transaction`.

 - [x] harmonize timestamp types
 - [x] define and use boilerplate-reducing convenience functions

**Comment by elielnfinic** [comment]
Is there anybody working on this?

**Comment by dan-da** [comment]
@elielnfinic no one is working on it that I know of.  A PR would be welcome.

**Comment by dan-da** [comment]
@aszepieniec With #124 merged, maybe now is a good time to get 9e55a5b into master?   I'm guessing there might be some conflicts to resolve.

**Comment by aszepieniec** [comment]
> @aszepieniec With https://github.com/Neptune-Crypto/neptune-core/pull/124 merged, maybe now is a good time to get https://github.com/Neptune-Crypto/neptune-core/commit/9e55a5b62afec6922155b008588480cdd0d235cd into master? I'm guessing there might be some conflicts to resolve.

Yes it is. No time like the present.
