### ISSUE TITLE
Write to disk all UTXO notifications that come from own client

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-core#137]
As I realized when discussing #136 we don't store UTXO notifications to disks. This means that if a client creates a transaction with a change UTXO and then shuts down before this transaction is included in a block, the change UTXO is not discovered by the client. #5 aims to address this issue in a fully recoverable fool proof way, but I think we should also just store the UTXO notifications to disk, *iff* they are worthy of storing to disk, that is -- this could be that they have a sufficiently high credibility, or, preferably just that they originate from the running instance, i.e. are of type `UtxoNotifier::OwnMiner`, `UtxoNotifier::Cli`, or `UtxoNotifier::Myself`.

**Comment by dan-da** [comment]
yeah, so [here](https://github.com/Neptune-Crypto/neptune-core/pull/136#issuecomment-2059627858) I am asking:

1. why a change UTXO is treated differently from any other incoming UTXO
2. why a change UTXO is treated differently from a UTXO that I am sending to my own wallet address, eg if splitting an existing wallet UTXO.

It seems we have two different ways of processing incoming UTXOs:  expected_utxos and announcements.  I presume there is a good reason, but I'd like to have a more thorough understanding before making any changes, especially as the asymmetry highlighted in (2) bothers me.  

And generally it just seems simpler and easier to maintain to have a single mechanism.

**Comment by dan-da** [comment]
closed by 232e852
