### ISSUE TITLE
Prune Abandoned UTXOs

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#17]
The node periodically runs a maintenance task to try to synchronize the membership proofs of owned UTXOs. But when the owned UTXOs live on an abandoned chain whose last common ancestor with the canonical one was deep enough, it's probably better to delete them.

 - [ ] write logic for
   - [ ] determining whether a UTXO should be deleted
   - [ ] deleting it 
 - [ ] write a command for the command-line interface
 - [ ] implement the RPC call on the client side

**Comment by Sword-Smith** [comment]
We're using `DbtVec` to store monitored UTXOs. And we cannot delete from the middle of a list, we only have a `pop` method to delete from the end of a list. Intead, I suggest we mark `MonitoredUtxo` in the database as `abandoned` and adapt the rest of the logic to deal with that.

**Comment by Sword-Smith** [comment]
`MonitoredUtxo` now has the field `abandoned_at`. This field can be populated by calling the `prune_abandoned_monitored_utxos` RPC endpoint`.  That endpoint is accessible through the CLI command `PruneAbandonedMonitoredUtxos`.
