### ISSUE TITLE
ExpectedUtxo not persisted, can lead to loss of funds.

### ISSUE THREAD

**Issue by dan-da** [Neptune-Crypto/neptune-core#172]
disclaimer:  I'm making a preliminary report so this doesn't get forgotten. I intend to make a test case to verify this issue is real, but from reading through relevant code I believe it is.

disclaimer2: this may be a known todo item on a list somewhere. 

If I've missed something, please correct and close if appropriate.

summary: if a node is stopped after sending a transaction (using off-chain utxo notification for change) but before the transaction is confirmed in a block then the utxo sent to change address is lost and can never be claimed.

steps to reproduce:   (I have not done this yet)

 1. check initiial wallet balance and record it.
 2. send funds to 3rd party, with some change going back to own wallet.
 3. shutdown wallet.
 4. wait for a block to be mined by another node.
 5. restart node.
 6. ensure tip of node has the mined block.
 7.  check wallet balance.

correct outcome: the balance should be original balance - send amount - fee.
predicted outcome:  the balance will be original balance - send amount - change amount - fee.

why would this happen?

because ExpectedUtxo are not persisted to disk, only MonitoredUtxo.   The former are converted into the latter after a block is mined.   So ExpectedUtxo live only in RAM (inside UtxoNotificationPool) and there exists a window of time during which the ExpectedUtxo can be lost if the node is shutdown.  This could be as bad as losing 100% of wallet funds.

Example scenario:

1. Alice starts her node, syncs, sends funds Bob, and immediately shuts down.
2. A week later, Alice starts her node again and is surprised that her wallet is now lower than expected.

This seems likely to be a common usage pattern.  (and even more so for light nodes)

Suggested fix:   We might consider adding a field expected_utxos: DbtVec<ExpectedUtxos> into RustyWalletDatabase.  This would store expected_utxos alongside monitored_utxos in the wallet db.   Alternatively a separate DB file could be utilized within UtxoNotificationPool.

**Comment by aszepieniec** [comment]
Agreed -- with both the analysis and the proposed fix.

**Comment by dan-da** [comment]
ok, I will make this my next priority then.

**Comment by dan-da** [comment]
this may be a dup of #157, or at least they are related.
