### ISSUE TITLE
Dashboard Can Induce Daemon Hang

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#18]
Running the dashboard for a long period of time eventually causes the daemon to hang. I used to think this was due to UTXO membership proof maintenance, but my most recent experience does not seem related to this.

The behavior is consistent with the hypothesis that there is a race condition between the RPC server (doing some job for the dashboard) and other client threads. Most likely, one or both threads acquire locks out of the canonical order.

Incidentally, it is less of a problem if an RPC call times out or comes back without result, compared to a timeout or negative result in any other thread of the client. Therefore, I would argue that the RPC server should use a different type of lock -- either try-locks that return a result immediately, or locks that can timeout after x seconds, as opposed to locks that stall until success.

**Comment by dan-da** [comment]
if a deadlock issue, [this](https://github.com/Neptune-Crypto/neptune-core/issues/64#issuecomment-1791395256) might help.

**Comment by dan-da** [comment]
I believe this was fixed in 1a97899191215b1af385a2ed047829dfa6fe3f29 and/or fa89d0414f6d95cd7407c67e15e00cdc06b9c121.
