### ISSUE TITLE
Report Verbosely on Peer Discovery Process

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#19]
I ran into [tekkac](https://github.com/tekkac/) today and he informed me that his node was only able to connect to one other node. Upon restarting the node there was some information about initiating peer discovery, but not enough information to debug the issue. It would be nice to have more fine-grained information to debug issues like this one. For instance:
 - [x] which peer lists do my peers respond with?
 - [ ] which of them am I (not) attempting to establish a connection to and why?

**Comment by dan-da** [comment]
related:  #105 improves logging with respect to whether connect is allowed or not for each peer. 

[sample log](https://github.com/Neptune-Crypto/neptune-core/files/14230995/peer2-readable.log)

**Comment by Sword-Smith** [comment]
Closed by 628c32e0d3cccf4818515bb6c077a6177b2eb2a1
