### ISSUE TITLE
`SpendingKey` fields should not be public

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-core#193]
This struct is leaking abstractions. Let's make the fields private.

**Comment by dan-da** [comment]
`SpendingKey` is an enum.

```
pub enum SpendingKey {
    /// a key from [generation_address]
    Generation(generation_address::GenerationSpendingKey),

    /// a [symmetric_key]
    Symmetric(symmetric_key::SymmetricKey),
}
```

I think you must mean `GenerationSpendingKey` and `GenerationReceivingAddress`, both of which presently have pub fields.

I agree they should be private.
