### ISSUE TITLE
Logging Verbosity as Command-Line Parameter

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#21]
Currently, the verbosity level of the logger is configured via environment variables. It would be nice to determine them via command-line arguments. This would bring the advantage of being able to turn them on or off via the command-line interface without restarting the node.

**Comment by Sword-Smith** [comment]
I don't think the logging framework supports this. The environment variable to use is `RUST_LOG`. Allowed values are `trace`, `debug`, `info`, `warn`, and `error`. Log-levels of sub-modules can be controlled by this syntax: ` RUST_LOG='debug,tarpc=warn'` or `RUST_LOG='info,neptune_cash=trace`.
