### ISSUE TITLE
We may be aborting composing unnecessarily in send RPC().

### ISSUE THREAD

**Issue by dan-da** [Neptune-Crypto/neptune-core#253]
The send() RPC call sends a message that pauses the miner to pause while the transaction is being created, and then resumes it afterward.

Except it doesn't really "pause" and "resume".   It actually aborts the composing (or guessing) tasks and restarts them later.  For guessing, this isn't really a problem because each guess is independent of any that came before.   However for composing we may be losing minutes worth of work when the task is aborted.

This then begs the question:  why are are doing this pause/resume and is it necessary?

I believe (best guess) it was originally being done to prevent CPU contention between the mining activity and the proof-generation for the new tx.

However there should no longer be any such contention.   Tx are created within send() as PrimitiveWitness (in milliseconds). 

ProofCollection and SingleProof are generated later, asynchronously in the job-queue, where they are serialized between composing jobs in the mining thread.

In other words, I don't see that the pause/resume is doing any good, and it is clearly doing harm.

As such, I believe it should be removed.

Opening this issue for comment before I do so.

Worth further note:  while researching this I discovered a bug in send(), whereby it pauses the miner, creates the tx, and then returns early without unpausing if create_transaction() returns an error.   I was able to easily hit this bug in the dashboard just by sending a tx with too large of an amount, after which mining remains paused.  My preferred fix is of course just to remove this pause/unpause mechanism from send.

rpc_server.rs
```
        let was_mining = self.state.mining().await;
        if was_mining {
            let _ = self
                .rpc_server_to_main_tx
                .send(RPCServerToMain::PauseMiner)
                .await;
        }
```

main_loop.rs
```
            RPCServerToMain::PauseMiner => {
                info!("Received RPC request to stop miner");

                self.main_to_miner_tx.send(MainToMiner::StopMining);
                Ok(false)
```

mine_loop.rs
```
                    MainToMiner::StopMining => {
                        pause_mine = true;

                        if let Some(gt) = guesser_task {
                            gt.abort();
                            debug!("Abort-signal sent to guesser worker.");
                        }
                        if !composer_task.is_finished() {
                            composer_task.abort();
                            debug!("Abort-signal sent to composer worker.");
                        }
                    }
```

**Comment by dan-da** [comment]
yeah, as a test I removed the paused/unpaused from send() and was able to send a Tx no problem while composing.    The composer is at 565 seconds after the send.  Whereas previously it would restart at 0 seconds, throwing away over 9 minutes of work.

**Comment by Sword-Smith** [comment]
This was originally written to prevent PoW guessing to conflict with proving. As a rule of thumb I would say that a composer should not initiate any transactions.

That being said: Now that the RPC Server only creates primitive witnesses, this feature has lost its purpose. Please remove.
