### ISSUE TITLE
Dashboard reports balances on stale chains

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#3]
If you were mining on a chain that has since been abandoned in favor of another one, your UTXO membership proofs won't be able to synchronize. But the balance reported by the dashboard still includes unsynked UTXOs. It should report only the balance of synked UTXOs.

**Comment by Sword-Smith** [comment]
You probably want to get the balance from the `get_wallet_status_from_lock` method on the [WalletState](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) struct.

**Comment by Sword-Smith** [comment]
Maybe we even want to remove the endpoint `get_balance` in `rpc_server.rs`? That would force the developer to use `get_wallet_status` and to consider what kind of numbers to use.
