### ISSUE TITLE
dashboard detecting spurious key events on windows

### ISSUE THREAD

**Issue by jan-ferdinand** [Neptune-Crypto/neptune-core#65]
If I remember correctly, and without access to a machine to test this on, there are spurious key events registered when the dashboard is run on windows. According to [this](https://ratatui-org.github.io/ratatui-async-template/02-structure.html#admonition-warning):

> [You] might use the following code for sending key presses:
>```rust
>  CrosstermEvent::Key(e) => tx.send(Event::Key(e)),
>```
>
> However, on Windows, when using `Crossterm`, this will send the same `Event::Key(e)` twice; one for when you press the key, i.e. `KeyEventKind::Press` and one for when you release the key, i.e. `KeyEventKind::Release`. On MacOS and Linux only `KeyEventKind::Press` kinds of key event is generated.
>
> To make the code work as expected across all platforms, you can do this instead:
>
> ```rust
>  CrosstermEvent::Key(key) => {
>    if key.kind == KeyEventKind::Press {
>      event_tx.send(Event::Key(key)).unwrap();
>    }
>  },
>```

This might help alleviate the issue.

**Comment by dan-da** [comment]
Nice catch.  I will have a look.

**Comment by Sword-Smith** [comment]
dashboard works well on Windows now :)
