### ISSUE TITLE
Show list of banned peers

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-core#70]
We're unfortunately struggling a bit with connection issues and fork resolutions. To get a better idea of what's going on, we should either have a CLI option to list all banned peers and/or be able to view this in the dashboard, as I think this plays a role in that issue.

Be mindful, though, that the way to get the list of all banned peers currently requires iterating over all entries in a level-db database, which is a very slow operation with the library we are using. To fix this a new table could be added, or maybe there are other possibilities.

**Comment by dan-da** [comment]
Closed by e4b65fbc3d38243b65e6afde7e2ab4535d46b866
