### ISSUE TITLE
How do we ensure we don't connect to the same peer multiple times?

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-core#8]
If a malicious peer wanted to make multiple connections to a client, they could do so by changing the instance ID for each new connection, as we're currently only checking the socket address for duplicates. If we checked the IP address for duplicates, maybe this attack would be harder?

**Comment by sshine** [comment]
https://darknetone.com/tor-merges-proof-of-work-to-combat-ddos-attacks/

https://gitlab.torproject.org/tpo/core/tor/-/merge_requests/702

**Comment by dan-da** [comment]
we should probably check what bitcoin does.
