### ISSUE TITLE
installation instructions for windows and mac

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#84]
Right now the only installation instructions are for linux (and in fact, Debian / Ubuntu). Let's support other platforms also.

 - [ ] Windows
 - [ ] MacOS

**Comment by elielnfinic** [comment]
I think this has been done. Am I right? @aszepieniec

**Comment by aszepieniec** [comment]
The README certainly has instructions for Windows but not for MacOS, as far as I can tell. Are they the same? Do they work? I am happy to close this issue once someone confirms that they ran the instructions and that they work.
