### ISSUE TITLE
show location of wallet.dat

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#87]
Where was my wallet located again? I suggest adding a command to `neptune-cli` that can save a lot of headache. Just show the location of the wallet.

**Comment by aszepieniec** [comment]
Note that `neptune-cli generate-wallet` does show the location already. But there is nothing about this command that signals it will tell you where the file is located.

**Comment by Sword-Smith** [comment]
Sounds good to me
