### ISSUE TITLE
verify MMR from nondeterministic input instead of memory

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#96]
One step of the removal record integrity program entails verifying MMR membership proofs. These proofs, which are essentially Merkle paths, are read from memory instead of nondeterministically divined. Roughly 20% of the program's cycles are spent on this step, but it should be a lot less after switching to nondeterministic input.

**Comment by Sword-Smith** [comment]
`RemovalRecordsIntegrity` now verifies the MMR authentication paths from secret-it. Unfortunately the entire removal records are hashed though, so there's still plenty room for improvement if we want a faster `RemovalRecordsIntegrity` program.
